### ISSUE TITLE
Relicense under MIT.

### ISSUE THREAD

**Issue by Gathros** [algorithm-archivists/GathVL#2]
Signed: 
[x] Gathros
[ ] @Gustorn 

I agree to have all of my previous and future commits to this repository licensed under the MIT license, as found in LICENSE.md.

**Comment by Gustorn** [comment]
Sure, go ahead

**Comment by leios** [comment]
MIT license added here: https://github.com/algorithm-archivists/GathVL/commit/74d02627f4811e97ece40f2dca03a538e7f1ed09
